class RoleEntity {
  roleId: string;
  roleName: string;
  roleCode: string;
  rolePermissions: [];
  constructor(role?) {
    if (!role) return null;
    Object.assign(this, role);
  }

  static createListRole(listRole) {
    if (!Array.isArray(listRole)) return [];
    return listRole.map((Role) => {
      return new RoleEntity(Role);
    });
  }
}



export default RoleEntity;


// Generated by https://quicktype.io

